// Code generated by qtc from "baked_in.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line baked_in.qtpl:1
package templates

//line baked_in.qtpl:1
import "github.com/jamillosantos/go-validator"

//line baked_in.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line baked_in.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line baked_in.qtpl:4
func StreamEnsureStringPointerSafety(qw422016 *qt422016.Writer, field *validator.FieldData) {
//line baked_in.qtpl:6
	var (
		prefix = ""
	)
	if field.IsPointer {
		prefix = "*"
	}

//line baked_in.qtpl:12
	qw422016.N().S(`	if `)
//line baked_in.qtpl:13
	if field.IsPointer {
//line baked_in.qtpl:13
		qw422016.N().S(`v.`)
//line baked_in.qtpl:13
		qw422016.E().S(field.Name)
//line baked_in.qtpl:13
		qw422016.N().S(` == nil || `)
//line baked_in.qtpl:13
	}
//line baked_in.qtpl:13
	qw422016.E().S(prefix)
//line baked_in.qtpl:13
	qw422016.N().S(`v.`)
//line baked_in.qtpl:13
	qw422016.E().S(field.Name)
//line baked_in.qtpl:13
	qw422016.N().S(` == "" {
		return true
	}
`)
//line baked_in.qtpl:16
}

//line baked_in.qtpl:16
func WriteEnsureStringPointerSafety(qq422016 qtio422016.Writer, field *validator.FieldData) {
//line baked_in.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:16
	StreamEnsureStringPointerSafety(qw422016, field)
//line baked_in.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:16
}

//line baked_in.qtpl:16
func EnsureStringPointerSafety(field *validator.FieldData) string {
//line baked_in.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:16
	WriteEnsureStringPointerSafety(qb422016, field)
//line baked_in.qtpl:16
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:16
	return qs422016
//line baked_in.qtpl:16
}

//line baked_in.qtpl:18
func StreamEnsureNumericPointerSafety(qw422016 *qt422016.Writer, field *validator.FieldData) {
//line baked_in.qtpl:20
	var (
		prefix = ""
	)
	if field.IsPointer {
		prefix = "*"
	}

//line baked_in.qtpl:26
	qw422016.N().S(`	if `)
//line baked_in.qtpl:27
	if field.IsPointer {
//line baked_in.qtpl:27
		qw422016.N().S(`v.`)
//line baked_in.qtpl:27
		qw422016.E().S(field.Name)
//line baked_in.qtpl:27
		qw422016.N().S(` == nil || `)
//line baked_in.qtpl:27
	}
//line baked_in.qtpl:27
	qw422016.E().S(prefix)
//line baked_in.qtpl:27
	qw422016.N().S(`v.`)
//line baked_in.qtpl:27
	qw422016.E().S(field.Name)
//line baked_in.qtpl:27
	qw422016.N().S(` == 0 {
		return true
	}
`)
//line baked_in.qtpl:30
}

//line baked_in.qtpl:30
func WriteEnsureNumericPointerSafety(qq422016 qtio422016.Writer, field *validator.FieldData) {
//line baked_in.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:30
	StreamEnsureNumericPointerSafety(qw422016, field)
//line baked_in.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:30
}

//line baked_in.qtpl:30
func EnsureNumericPointerSafety(field *validator.FieldData) string {
//line baked_in.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:30
	WriteEnsureNumericPointerSafety(qb422016, field)
//line baked_in.qtpl:30
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:30
	return qs422016
//line baked_in.qtpl:30
}

//line baked_in.qtpl:32
func StreamHasValueValidation(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData) {
//line baked_in.qtpl:32
	qw422016.N().S(`func () bool {
`)
//line baked_in.qtpl:34
	if field.IsPointer {
//line baked_in.qtpl:34
		qw422016.N().S(`	if v.`)
//line baked_in.qtpl:35
		qw422016.E().S(field.Name)
//line baked_in.qtpl:35
		qw422016.N().S(` == nil {
		return false
	}
`)
//line baked_in.qtpl:38
	}
//line baked_in.qtpl:40
	var (
		prefix = ""
		zero   = ""
	)
	if field.IsPointer {
		prefix = "*"
	}
	if field.IsNumeric {
		zero = "0"
	}
	if field.IsBoolean {
		zero = "false"
	}
	if field.IsString {
		zero = `""`
	}

//line baked_in.qtpl:57
	if field.IsArray {
//line baked_in.qtpl:57
		qw422016.N().S(`	return len(v.`)
//line baked_in.qtpl:58
		qw422016.E().S(field.Name)
//line baked_in.qtpl:58
		qw422016.N().S(`) != 0
`)
//line baked_in.qtpl:59
	} else {
//line baked_in.qtpl:59
		qw422016.N().S(`	return `)
//line baked_in.qtpl:60
		qw422016.E().S(prefix)
//line baked_in.qtpl:60
		qw422016.N().S(`v.`)
//line baked_in.qtpl:60
		qw422016.E().S(field.Name)
//line baked_in.qtpl:60
		qw422016.N().S(` != `)
//line baked_in.qtpl:60
		streamunesc(qw422016, zero)
//line baked_in.qtpl:60
		qw422016.N().S(`
`)
//line baked_in.qtpl:61
	}
//line baked_in.qtpl:61
	qw422016.N().S(`}`)
//line baked_in.qtpl:62
}

//line baked_in.qtpl:62
func WriteHasValueValidation(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData) {
//line baked_in.qtpl:62
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:62
	StreamHasValueValidation(qw422016, s, field)
//line baked_in.qtpl:62
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:62
}

//line baked_in.qtpl:62
func HasValueValidation(s *validator.StructData, field *validator.FieldData) string {
//line baked_in.qtpl:62
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:62
	WriteHasValueValidation(qb422016, s, field)
//line baked_in.qtpl:62
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:62
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:62
	return qs422016
//line baked_in.qtpl:62
}

//line baked_in.qtpl:64
func StreamHasValue(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:64
	qw422016.N().S(`	if !(`)
//line baked_in.qtpl:65
	StreamHasValueValidation(qw422016, s, field)
//line baked_in.qtpl:65
	qw422016.N().S(`)() {
		verr = append(verr, validator.NewFieldError(validator.ErrRequired, "required", "`)
//line baked_in.qtpl:66
	qw422016.E().J(field.Identifier)
//line baked_in.qtpl:66
	qw422016.N().S(`", v.`)
//line baked_in.qtpl:66
	qw422016.E().S(field.Name)
//line baked_in.qtpl:66
	qw422016.N().S(`))
	}
`)
//line baked_in.qtpl:68
}

//line baked_in.qtpl:68
func WriteHasValue(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:68
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:68
	StreamHasValue(qw422016, s, field, validation)
//line baked_in.qtpl:68
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:68
}

//line baked_in.qtpl:68
func HasValue(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) string {
//line baked_in.qtpl:68
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:68
	WriteHasValue(qb422016, s, field, validation)
//line baked_in.qtpl:68
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:68
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:68
	return qs422016
//line baked_in.qtpl:68
}

//line baked_in.qtpl:70
func StreamIsDefault(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:70
	qw422016.N().S(`	if (`)
//line baked_in.qtpl:71
	StreamHasValueValidation(qw422016, s, field)
//line baked_in.qtpl:71
	qw422016.N().S(`)() {
		verr = append(verr, validator.NewFieldError(validator.ErrIsDefault, "`)
//line baked_in.qtpl:72
	qw422016.E().J(field.Identifier)
//line baked_in.qtpl:72
	qw422016.N().S(`", v.`)
//line baked_in.qtpl:72
	qw422016.E().S(field.Name)
//line baked_in.qtpl:72
	qw422016.N().S(`))
	}
`)
//line baked_in.qtpl:74
}

//line baked_in.qtpl:74
func WriteIsDefault(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:74
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:74
	StreamIsDefault(qw422016, s, field, validation)
//line baked_in.qtpl:74
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:74
}

//line baked_in.qtpl:74
func IsDefault(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) string {
//line baked_in.qtpl:74
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:74
	WriteIsDefault(qb422016, s, field, validation)
//line baked_in.qtpl:74
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:74
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:74
	return qs422016
//line baked_in.qtpl:74
}

//line baked_in.qtpl:76
func StreamNumberValidation(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData, sign string) {
//line baked_in.qtpl:76
	qw422016.N().S(`func () bool {
`)
//line baked_in.qtpl:79
	var (
		prefix = ""
	)
	if field.IsPointer {
		prefix = "*"
	}

//line baked_in.qtpl:85
	qw422016.N().S(`	if `)
//line baked_in.qtpl:86
	if field.IsPointer {
//line baked_in.qtpl:86
		qw422016.N().S(`v.`)
//line baked_in.qtpl:86
		qw422016.E().S(field.Name)
//line baked_in.qtpl:86
		qw422016.N().S(` == nil || `)
//line baked_in.qtpl:86
	}
//line baked_in.qtpl:86
	qw422016.E().S(prefix)
//line baked_in.qtpl:86
	qw422016.N().S(`v.`)
//line baked_in.qtpl:86
	qw422016.E().S(field.Name)
//line baked_in.qtpl:86
	qw422016.N().S(` == 0 {
		return true
	}
	return `)
//line baked_in.qtpl:89
	qw422016.E().S(prefix)
//line baked_in.qtpl:89
	qw422016.N().S(`v.`)
//line baked_in.qtpl:89
	qw422016.E().S(field.Name)
//line baked_in.qtpl:89
	qw422016.N().S(` `)
//line baked_in.qtpl:89
	streamunesc(qw422016, sign)
//line baked_in.qtpl:89
	qw422016.N().S(` `)
//line baked_in.qtpl:89
	streamunesc(qw422016, validation.Params[0])
//line baked_in.qtpl:89
	qw422016.N().S(`
}`)
//line baked_in.qtpl:90
}

//line baked_in.qtpl:90
func WriteNumberValidation(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData, sign string) {
//line baked_in.qtpl:90
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:90
	StreamNumberValidation(qw422016, s, field, validation, sign)
//line baked_in.qtpl:90
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:90
}

//line baked_in.qtpl:90
func NumberValidation(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData, sign string) string {
//line baked_in.qtpl:90
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:90
	WriteNumberValidation(qb422016, s, field, validation, sign)
//line baked_in.qtpl:90
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:90
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:90
	return qs422016
//line baked_in.qtpl:90
}

//line baked_in.qtpl:92
func StreamLenValidation(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData, sign string) {
//line baked_in.qtpl:92
	qw422016.N().S(`func () bool {
`)
//line baked_in.qtpl:95
	var (
		prefix = ""
	)
	if field.IsPointer {
		prefix = "*"
	}

//line baked_in.qtpl:102
	if field.IsString && field.IsPointer {
//line baked_in.qtpl:102
		qw422016.N().S(`	if `)
//line baked_in.qtpl:103
		if field.IsPointer {
//line baked_in.qtpl:103
			qw422016.N().S(`v.`)
//line baked_in.qtpl:103
			qw422016.E().S(field.Name)
//line baked_in.qtpl:103
			qw422016.N().S(` == nil || `)
//line baked_in.qtpl:103
		}
//line baked_in.qtpl:103
		qw422016.E().S(prefix)
//line baked_in.qtpl:103
		qw422016.N().S(`v.`)
//line baked_in.qtpl:103
		qw422016.E().S(field.Name)
//line baked_in.qtpl:103
		qw422016.N().S(` == "" {
		return true
	}
`)
//line baked_in.qtpl:106
	}
//line baked_in.qtpl:106
	qw422016.N().S(`	return len(`)
//line baked_in.qtpl:107
	qw422016.E().S(prefix)
//line baked_in.qtpl:107
	qw422016.N().S(`v.`)
//line baked_in.qtpl:107
	qw422016.E().S(field.Name)
//line baked_in.qtpl:107
	qw422016.N().S(`) == 0 || len(`)
//line baked_in.qtpl:107
	qw422016.E().S(prefix)
//line baked_in.qtpl:107
	qw422016.N().S(`v.`)
//line baked_in.qtpl:107
	qw422016.E().S(field.Name)
//line baked_in.qtpl:107
	qw422016.N().S(`) `)
//line baked_in.qtpl:107
	streamunesc(qw422016, sign)
//line baked_in.qtpl:107
	qw422016.N().S(` `)
//line baked_in.qtpl:107
	streamunesc(qw422016, validation.Params[0])
//line baked_in.qtpl:107
	qw422016.N().S(`
}`)
//line baked_in.qtpl:108
}

//line baked_in.qtpl:108
func WriteLenValidation(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData, sign string) {
//line baked_in.qtpl:108
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:108
	StreamLenValidation(qw422016, s, field, validation, sign)
//line baked_in.qtpl:108
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:108
}

//line baked_in.qtpl:108
func LenValidation(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData, sign string) string {
//line baked_in.qtpl:108
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:108
	WriteLenValidation(qb422016, s, field, validation, sign)
//line baked_in.qtpl:108
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:108
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:108
	return qs422016
//line baked_in.qtpl:108
}

//line baked_in.qtpl:110
func StreamGte(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:110
	qw422016.N().S(`	if (`)
//line baked_in.qtpl:111
	StreamNumberValidation(qw422016, s, field, validation, ">=")
//line baked_in.qtpl:111
	qw422016.N().S(`)() {
		verr = append(verr, validator.NewFieldError(validator.ErrIsDefault, "gte", "`)
//line baked_in.qtpl:112
	qw422016.E().J(field.Identifier)
//line baked_in.qtpl:112
	qw422016.N().S(`", v.`)
//line baked_in.qtpl:112
	qw422016.E().S(field.Name)
//line baked_in.qtpl:112
	qw422016.N().S(`))
	}
`)
//line baked_in.qtpl:114
}

//line baked_in.qtpl:114
func WriteGte(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:114
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:114
	StreamGte(qw422016, s, field, validation)
//line baked_in.qtpl:114
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:114
}

//line baked_in.qtpl:114
func Gte(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) string {
//line baked_in.qtpl:114
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:114
	WriteGte(qb422016, s, field, validation)
//line baked_in.qtpl:114
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:114
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:114
	return qs422016
//line baked_in.qtpl:114
}

//line baked_in.qtpl:116
func StreamLte(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:116
	qw422016.N().S(`	if (`)
//line baked_in.qtpl:117
	StreamNumberValidation(qw422016, s, field, validation, "<=")
//line baked_in.qtpl:117
	qw422016.N().S(`)() {
		verr = append(verr, validator.NewFieldError(validator.ErrIsDefault, "lte", "`)
//line baked_in.qtpl:118
	qw422016.E().J(field.Identifier)
//line baked_in.qtpl:118
	qw422016.N().S(`", v.`)
//line baked_in.qtpl:118
	qw422016.E().S(field.Name)
//line baked_in.qtpl:118
	qw422016.N().S(`))
	}
`)
//line baked_in.qtpl:120
}

//line baked_in.qtpl:120
func WriteLte(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:120
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:120
	StreamLte(qw422016, s, field, validation)
//line baked_in.qtpl:120
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:120
}

//line baked_in.qtpl:120
func Lte(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) string {
//line baked_in.qtpl:120
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:120
	WriteLte(qb422016, s, field, validation)
//line baked_in.qtpl:120
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:120
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:120
	return qs422016
//line baked_in.qtpl:120
}

//line baked_in.qtpl:122
func StreamRegexValidation(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData, regexpRule string) {
//line baked_in.qtpl:122
	qw422016.N().S(`func () bool {
	`)
//line baked_in.qtpl:124
	StreamEnsureStringPointerSafety(qw422016, field)
//line baked_in.qtpl:124
	qw422016.N().S(`
`)
//line baked_in.qtpl:126
	var (
		prefix = ""
	)
	if field.IsPointer {
		prefix = "*"
	}

//line baked_in.qtpl:132
	qw422016.N().S(`	return `)
//line baked_in.qtpl:133
	qw422016.E().S(regexpRule)
//line baked_in.qtpl:133
	qw422016.N().S(`.MatchString(`)
//line baked_in.qtpl:133
	qw422016.E().S(prefix)
//line baked_in.qtpl:133
	qw422016.N().S(`v.`)
//line baked_in.qtpl:133
	qw422016.E().S(field.Name)
//line baked_in.qtpl:133
	qw422016.N().S(`)
}`)
//line baked_in.qtpl:134
}

//line baked_in.qtpl:134
func WriteRegexValidation(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData, regexpRule string) {
//line baked_in.qtpl:134
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:134
	StreamRegexValidation(qw422016, s, field, validation, regexpRule)
//line baked_in.qtpl:134
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:134
}

//line baked_in.qtpl:134
func RegexValidation(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData, regexpRule string) string {
//line baked_in.qtpl:134
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:134
	WriteRegexValidation(qb422016, s, field, validation, regexpRule)
//line baked_in.qtpl:134
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:134
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:134
	return qs422016
//line baked_in.qtpl:134
}

//line baked_in.qtpl:136
func StreamEmail(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:136
	qw422016.N().S(`	if !(`)
//line baked_in.qtpl:137
	StreamRegexValidation(qw422016, s, field, validation, "validator.EmailRegex")
//line baked_in.qtpl:137
	qw422016.N().S(`)() {
		verr = append(verr, validator.NewFieldError(validator.ErrEmail, "email", "`)
//line baked_in.qtpl:138
	qw422016.E().J(field.Identifier)
//line baked_in.qtpl:138
	qw422016.N().S(`", v.`)
//line baked_in.qtpl:138
	qw422016.E().S(field.Name)
//line baked_in.qtpl:138
	qw422016.N().S(`))
	}
`)
//line baked_in.qtpl:140
}

//line baked_in.qtpl:140
func WriteEmail(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:140
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:140
	StreamEmail(qw422016, s, field, validation)
//line baked_in.qtpl:140
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:140
}

//line baked_in.qtpl:140
func Email(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) string {
//line baked_in.qtpl:140
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:140
	WriteEmail(qb422016, s, field, validation)
//line baked_in.qtpl:140
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:140
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:140
	return qs422016
//line baked_in.qtpl:140
}

//line baked_in.qtpl:142
func StreamMin(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:143
	if field.IsNumeric {
//line baked_in.qtpl:143
		qw422016.N().S(`	if !(`)
//line baked_in.qtpl:144
		StreamNumberValidation(qw422016, s, field, validation, ">=")
//line baked_in.qtpl:144
		qw422016.N().S(`)() {
		verr = append(verr, validator.NewFieldError(validator.ErrMin, "min", "`)
//line baked_in.qtpl:145
		qw422016.E().J(field.Identifier)
//line baked_in.qtpl:145
		qw422016.N().S(`", v.`)
//line baked_in.qtpl:145
		qw422016.E().S(field.Name)
//line baked_in.qtpl:145
		qw422016.N().S(`))
	}
`)
//line baked_in.qtpl:147
	} else if field.IsArray || field.IsString {
//line baked_in.qtpl:147
		qw422016.N().S(`	if !(`)
//line baked_in.qtpl:148
		StreamLenValidation(qw422016, s, field, validation, ">=")
//line baked_in.qtpl:148
		qw422016.N().S(`)() {
		verr = append(verr, validator.NewFieldError(validator.ErrMin, "min", "`)
//line baked_in.qtpl:149
		qw422016.E().J(field.Identifier)
//line baked_in.qtpl:149
		qw422016.N().S(`", v.`)
//line baked_in.qtpl:149
		qw422016.E().S(field.Name)
//line baked_in.qtpl:149
		qw422016.N().S(`))
	}
`)
//line baked_in.qtpl:151
	} else {
//line baked_in.qtpl:153
		panic("field must be numeric, array or string")

//line baked_in.qtpl:155
	}
//line baked_in.qtpl:156
}

//line baked_in.qtpl:156
func WriteMin(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:156
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:156
	StreamMin(qw422016, s, field, validation)
//line baked_in.qtpl:156
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:156
}

//line baked_in.qtpl:156
func Min(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) string {
//line baked_in.qtpl:156
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:156
	WriteMin(qb422016, s, field, validation)
//line baked_in.qtpl:156
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:156
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:156
	return qs422016
//line baked_in.qtpl:156
}

//line baked_in.qtpl:158
func StreamMax(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:159
	if field.IsNumeric {
//line baked_in.qtpl:159
		qw422016.N().S(`	if !(`)
//line baked_in.qtpl:160
		StreamNumberValidation(qw422016, s, field, validation, "<=")
//line baked_in.qtpl:160
		qw422016.N().S(`)() {
		verr = append(verr, validator.NewFieldError(validator.ErrMax, "max", "`)
//line baked_in.qtpl:161
		qw422016.E().J(field.Identifier)
//line baked_in.qtpl:161
		qw422016.N().S(`", v.`)
//line baked_in.qtpl:161
		qw422016.E().S(field.Name)
//line baked_in.qtpl:161
		qw422016.N().S(`))
	}
`)
//line baked_in.qtpl:163
	} else if field.IsArray || field.IsString {
//line baked_in.qtpl:163
		qw422016.N().S(`	if !(`)
//line baked_in.qtpl:164
		StreamLenValidation(qw422016, s, field, validation, "<=")
//line baked_in.qtpl:164
		qw422016.N().S(`)() {
		verr = append(verr, validator.NewFieldError(validator.ErrMax, "max", "`)
//line baked_in.qtpl:165
		qw422016.E().J(field.Identifier)
//line baked_in.qtpl:165
		qw422016.N().S(`", v.`)
//line baked_in.qtpl:165
		qw422016.E().S(field.Name)
//line baked_in.qtpl:165
		qw422016.N().S(`))
	}
`)
//line baked_in.qtpl:167
	} else {
//line baked_in.qtpl:169
		panic("field must be numeric, array or string")

//line baked_in.qtpl:171
	}
//line baked_in.qtpl:172
}

//line baked_in.qtpl:172
func WriteMax(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:172
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:172
	StreamMax(qw422016, s, field, validation)
//line baked_in.qtpl:172
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:172
}

//line baked_in.qtpl:172
func Max(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) string {
//line baked_in.qtpl:172
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:172
	WriteMax(qb422016, s, field, validation)
//line baked_in.qtpl:172
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:172
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:172
	return qs422016
//line baked_in.qtpl:172
}

//line baked_in.qtpl:174
func StreamHexcolor(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:174
	qw422016.N().S(`	if v.`)
//line baked_in.qtpl:175
	qw422016.E().S(field.Name)
//line baked_in.qtpl:175
	qw422016.N().S(` != "" && !(`)
//line baked_in.qtpl:175
	StreamRegexValidation(qw422016, s, field, validation, "validator.HexcolorRegex")
//line baked_in.qtpl:175
	qw422016.N().S(`)() {
		verr = append(verr, validator.NewFieldError(validator.ErrIsDefault, "hexcolor", "`)
//line baked_in.qtpl:176
	qw422016.E().J(field.Identifier)
//line baked_in.qtpl:176
	qw422016.N().S(`", v.`)
//line baked_in.qtpl:176
	qw422016.E().S(field.Name)
//line baked_in.qtpl:176
	qw422016.N().S(`))
	}
`)
//line baked_in.qtpl:178
}

//line baked_in.qtpl:178
func WriteHexcolor(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:178
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:178
	StreamHexcolor(qw422016, s, field, validation)
//line baked_in.qtpl:178
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:178
}

//line baked_in.qtpl:178
func Hexcolor(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) string {
//line baked_in.qtpl:178
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:178
	WriteHexcolor(qb422016, s, field, validation)
//line baked_in.qtpl:178
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:178
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:178
	return qs422016
//line baked_in.qtpl:178
}

//line baked_in.qtpl:180
func StreamRGBa(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:180
	qw422016.N().S(`	if v.`)
//line baked_in.qtpl:181
	qw422016.E().S(field.Name)
//line baked_in.qtpl:181
	qw422016.N().S(` != "" && !(`)
//line baked_in.qtpl:181
	StreamRegexValidation(qw422016, s, field, validation, "validator.RgbaRegex")
//line baked_in.qtpl:181
	qw422016.N().S(`)() {
		verr = append(verr, validator.NewFieldError(validator.ErrIsDefault, "rgba", "`)
//line baked_in.qtpl:182
	qw422016.E().J(field.Identifier)
//line baked_in.qtpl:182
	qw422016.N().S(`", v.`)
//line baked_in.qtpl:182
	qw422016.E().S(field.Name)
//line baked_in.qtpl:182
	qw422016.N().S(`))
	}
`)
//line baked_in.qtpl:184
}

//line baked_in.qtpl:184
func WriteRGBa(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:184
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:184
	StreamRGBa(qw422016, s, field, validation)
//line baked_in.qtpl:184
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:184
}

//line baked_in.qtpl:184
func RGBa(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) string {
//line baked_in.qtpl:184
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:184
	WriteRGBa(qb422016, s, field, validation)
//line baked_in.qtpl:184
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:184
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:184
	return qs422016
//line baked_in.qtpl:184
}

//line baked_in.qtpl:186
func StreamRGB(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:186
	qw422016.N().S(`	if v.`)
//line baked_in.qtpl:187
	qw422016.E().S(field.Name)
//line baked_in.qtpl:187
	qw422016.N().S(` != "" && !(`)
//line baked_in.qtpl:187
	StreamRegexValidation(qw422016, s, field, validation, "validator.RgbRegex")
//line baked_in.qtpl:187
	qw422016.N().S(`)() {
		verr = append(verr, validator.NewFieldError(validator.ErrIsDefault, "rgb", "`)
//line baked_in.qtpl:188
	qw422016.E().J(field.Identifier)
//line baked_in.qtpl:188
	qw422016.N().S(`", v.`)
//line baked_in.qtpl:188
	qw422016.E().S(field.Name)
//line baked_in.qtpl:188
	qw422016.N().S(`))
	}
`)
//line baked_in.qtpl:190
}

//line baked_in.qtpl:190
func WriteRGB(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:190
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:190
	StreamRGB(qw422016, s, field, validation)
//line baked_in.qtpl:190
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:190
}

//line baked_in.qtpl:190
func RGB(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) string {
//line baked_in.qtpl:190
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:190
	WriteRGB(qb422016, s, field, validation)
//line baked_in.qtpl:190
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:190
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:190
	return qs422016
//line baked_in.qtpl:190
}
