// Code generated by qtc from "baked_in.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line baked_in.qtpl:1
package templates

//line baked_in.qtpl:1
import "github.com/jamillosantos/go-validator"

//line baked_in.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line baked_in.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line baked_in.qtpl:3
func StreamHasValueValidation(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData) {
//line baked_in.qtpl:3
	qw422016.N().S(`func () bool {
`)
//line baked_in.qtpl:5
	if field.IsPointer {
//line baked_in.qtpl:5
		qw422016.N().S(`	if v.`)
//line baked_in.qtpl:6
		qw422016.E().S(field.Name)
//line baked_in.qtpl:6
		qw422016.N().S(` == nil {
		return false
	}
`)
//line baked_in.qtpl:9
	}
//line baked_in.qtpl:11
	var (
		prefix = ""
		zero   = ""
	)
	if field.IsPointer {
		prefix = "*"
	}
	if field.IsNumeric {
		zero = "0"
	}
	if field.IsBoolean {
		zero = "false"
	}
	if field.IsString {
		zero = `""`
	}

//line baked_in.qtpl:28
	if field.IsArray {
//line baked_in.qtpl:28
		qw422016.N().S(`	if len(v.`)
//line baked_in.qtpl:29
		qw422016.E().S(field.Name)
//line baked_in.qtpl:29
		qw422016.N().S(`) == 0 {
		return false
	}
`)
//line baked_in.qtpl:32
	} else {
//line baked_in.qtpl:32
		qw422016.N().S(`	return `)
//line baked_in.qtpl:33
		qw422016.E().S(prefix)
//line baked_in.qtpl:33
		qw422016.N().S(`v.`)
//line baked_in.qtpl:33
		qw422016.E().S(field.Name)
//line baked_in.qtpl:33
		qw422016.N().S(` != `)
//line baked_in.qtpl:33
		streamunesc(qw422016, zero)
//line baked_in.qtpl:33
		qw422016.N().S(`
`)
//line baked_in.qtpl:34
	}
//line baked_in.qtpl:34
	qw422016.N().S(`}`)
//line baked_in.qtpl:35
}

//line baked_in.qtpl:35
func WriteHasValueValidation(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData) {
//line baked_in.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:35
	StreamHasValueValidation(qw422016, s, field)
//line baked_in.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:35
}

//line baked_in.qtpl:35
func HasValueValidation(s *validator.StructData, field *validator.FieldData) string {
//line baked_in.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:35
	WriteHasValueValidation(qb422016, s, field)
//line baked_in.qtpl:35
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:35
	return qs422016
//line baked_in.qtpl:35
}

//line baked_in.qtpl:37
func StreamHasValue(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:37
	qw422016.N().S(`	if !(`)
//line baked_in.qtpl:38
	StreamHasValueValidation(qw422016, s, field)
//line baked_in.qtpl:38
	qw422016.N().S(`)() {
		verr = append(verr, validator.NewFieldError(validator.ErrRequired, "required", "`)
//line baked_in.qtpl:39
	qw422016.E().J(field.Identifier)
//line baked_in.qtpl:39
	qw422016.N().S(`", v.`)
//line baked_in.qtpl:39
	qw422016.E().S(field.Name)
//line baked_in.qtpl:39
	qw422016.N().S(`))
	}
`)
//line baked_in.qtpl:41
}

//line baked_in.qtpl:41
func WriteHasValue(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:41
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:41
	StreamHasValue(qw422016, s, field, validation)
//line baked_in.qtpl:41
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:41
}

//line baked_in.qtpl:41
func HasValue(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) string {
//line baked_in.qtpl:41
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:41
	WriteHasValue(qb422016, s, field, validation)
//line baked_in.qtpl:41
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:41
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:41
	return qs422016
//line baked_in.qtpl:41
}

//line baked_in.qtpl:43
func StreamIsDefault(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:43
	qw422016.N().S(`	if (`)
//line baked_in.qtpl:44
	StreamHasValueValidation(qw422016, s, field)
//line baked_in.qtpl:44
	qw422016.N().S(`)() {
		verr = append(verr, validator.NewFieldError(validator.ErrIsDefault, "`)
//line baked_in.qtpl:45
	qw422016.E().J(field.Identifier)
//line baked_in.qtpl:45
	qw422016.N().S(`", v.`)
//line baked_in.qtpl:45
	qw422016.E().S(field.Name)
//line baked_in.qtpl:45
	qw422016.N().S(`))
	}
`)
//line baked_in.qtpl:47
}

//line baked_in.qtpl:47
func WriteIsDefault(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:47
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:47
	StreamIsDefault(qw422016, s, field, validation)
//line baked_in.qtpl:47
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:47
}

//line baked_in.qtpl:47
func IsDefault(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) string {
//line baked_in.qtpl:47
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:47
	WriteIsDefault(qb422016, s, field, validation)
//line baked_in.qtpl:47
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:47
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:47
	return qs422016
//line baked_in.qtpl:47
}

//line baked_in.qtpl:49
func StreamNumberValidation(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData, sign string) {
//line baked_in.qtpl:49
	qw422016.N().S(`func () bool {
`)
//line baked_in.qtpl:51
	if field.IsPointer {
//line baked_in.qtpl:51
		qw422016.N().S(`	if v.`)
//line baked_in.qtpl:52
		qw422016.E().S(field.Name)
//line baked_in.qtpl:52
		qw422016.N().S(` == nil {
		
		return true
	}
`)
//line baked_in.qtpl:56
	}
//line baked_in.qtpl:58
	var (
		prefix = ""
	)
	if field.IsPointer {
		prefix = "*"
	}

//line baked_in.qtpl:64
	qw422016.N().S(`	return `)
//line baked_in.qtpl:65
	qw422016.E().S(prefix)
//line baked_in.qtpl:65
	qw422016.N().S(`v.`)
//line baked_in.qtpl:65
	qw422016.E().S(field.Name)
//line baked_in.qtpl:65
	qw422016.N().S(` `)
//line baked_in.qtpl:65
	streamunesc(qw422016, sign)
//line baked_in.qtpl:65
	qw422016.N().S(` `)
//line baked_in.qtpl:65
	streamunesc(qw422016, validation.Params[0])
//line baked_in.qtpl:65
	qw422016.N().S(`
}`)
//line baked_in.qtpl:66
}

//line baked_in.qtpl:66
func WriteNumberValidation(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData, sign string) {
//line baked_in.qtpl:66
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:66
	StreamNumberValidation(qw422016, s, field, validation, sign)
//line baked_in.qtpl:66
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:66
}

//line baked_in.qtpl:66
func NumberValidation(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData, sign string) string {
//line baked_in.qtpl:66
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:66
	WriteNumberValidation(qb422016, s, field, validation, sign)
//line baked_in.qtpl:66
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:66
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:66
	return qs422016
//line baked_in.qtpl:66
}

//line baked_in.qtpl:68
func StreamGte(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:68
	qw422016.N().S(`	if (`)
//line baked_in.qtpl:69
	StreamNumberValidation(qw422016, s, field, validation, ">=")
//line baked_in.qtpl:69
	qw422016.N().S(`)() {
		verr = append(verr, validator.NewFieldError(validator.ErrIsDefault, "gte", "`)
//line baked_in.qtpl:70
	qw422016.E().J(field.Identifier)
//line baked_in.qtpl:70
	qw422016.N().S(`", v.`)
//line baked_in.qtpl:70
	qw422016.E().S(field.Name)
//line baked_in.qtpl:70
	qw422016.N().S(`))
	}
`)
//line baked_in.qtpl:72
}

//line baked_in.qtpl:72
func WriteGte(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:72
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:72
	StreamGte(qw422016, s, field, validation)
//line baked_in.qtpl:72
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:72
}

//line baked_in.qtpl:72
func Gte(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) string {
//line baked_in.qtpl:72
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:72
	WriteGte(qb422016, s, field, validation)
//line baked_in.qtpl:72
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:72
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:72
	return qs422016
//line baked_in.qtpl:72
}

//line baked_in.qtpl:74
func StreamLte(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:74
	qw422016.N().S(`	if (`)
//line baked_in.qtpl:75
	StreamNumberValidation(qw422016, s, field, validation, "<=")
//line baked_in.qtpl:75
	qw422016.N().S(`)() {
		verr = append(verr, validator.NewFieldError(validator.ErrIsDefault, "lte", "`)
//line baked_in.qtpl:76
	qw422016.E().J(field.Identifier)
//line baked_in.qtpl:76
	qw422016.N().S(`", v.`)
//line baked_in.qtpl:76
	qw422016.E().S(field.Name)
//line baked_in.qtpl:76
	qw422016.N().S(`))
	}
`)
//line baked_in.qtpl:78
}

//line baked_in.qtpl:78
func WriteLte(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:78
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:78
	StreamLte(qw422016, s, field, validation)
//line baked_in.qtpl:78
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:78
}

//line baked_in.qtpl:78
func Lte(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) string {
//line baked_in.qtpl:78
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:78
	WriteLte(qb422016, s, field, validation)
//line baked_in.qtpl:78
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:78
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:78
	return qs422016
//line baked_in.qtpl:78
}

//line baked_in.qtpl:81
func StreamRegexValidation(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData, regexpRule string) {
//line baked_in.qtpl:81
	qw422016.N().S(`func () bool {
`)
//line baked_in.qtpl:83
	if field.IsPointer {
//line baked_in.qtpl:83
		qw422016.N().S(`	if v.`)
//line baked_in.qtpl:84
		qw422016.E().S(field.Name)
//line baked_in.qtpl:84
		qw422016.N().S(` == nil {
		return true
	}
`)
//line baked_in.qtpl:87
	}
//line baked_in.qtpl:89
	var (
		prefix = ""
	)
	if field.IsPointer {
		prefix = "*"
	}

//line baked_in.qtpl:95
	qw422016.N().S(`	return `)
//line baked_in.qtpl:96
	qw422016.E().S(regexpRule)
//line baked_in.qtpl:96
	qw422016.N().S(`.MatchString(`)
//line baked_in.qtpl:96
	qw422016.E().S(prefix)
//line baked_in.qtpl:96
	qw422016.N().S(`v.`)
//line baked_in.qtpl:96
	qw422016.E().S(field.Name)
//line baked_in.qtpl:96
	qw422016.N().S(`)
}`)
//line baked_in.qtpl:97
}

//line baked_in.qtpl:97
func WriteRegexValidation(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData, regexpRule string) {
//line baked_in.qtpl:97
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:97
	StreamRegexValidation(qw422016, s, field, validation, regexpRule)
//line baked_in.qtpl:97
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:97
}

//line baked_in.qtpl:97
func RegexValidation(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData, regexpRule string) string {
//line baked_in.qtpl:97
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:97
	WriteRegexValidation(qb422016, s, field, validation, regexpRule)
//line baked_in.qtpl:97
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:97
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:97
	return qs422016
//line baked_in.qtpl:97
}

//line baked_in.qtpl:99
func StreamEmail(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:99
	qw422016.N().S(`	if !(`)
//line baked_in.qtpl:100
	StreamRegexValidation(qw422016, s, field, validation, "validator.EmailRegex")
//line baked_in.qtpl:100
	qw422016.N().S(`)() {
		verr = append(verr, validator.NewFieldError(validator.ErrIsDefault, "email", "`)
//line baked_in.qtpl:101
	qw422016.E().J(field.Identifier)
//line baked_in.qtpl:101
	qw422016.N().S(`", v.`)
//line baked_in.qtpl:101
	qw422016.E().S(field.Name)
//line baked_in.qtpl:101
	qw422016.N().S(`))
	}
`)
//line baked_in.qtpl:103
}

//line baked_in.qtpl:103
func WriteEmail(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:103
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:103
	StreamEmail(qw422016, s, field, validation)
//line baked_in.qtpl:103
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:103
}

//line baked_in.qtpl:103
func Email(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) string {
//line baked_in.qtpl:103
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:103
	WriteEmail(qb422016, s, field, validation)
//line baked_in.qtpl:103
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:103
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:103
	return qs422016
//line baked_in.qtpl:103
}

//line baked_in.qtpl:105
func StreamHexcolor(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:105
	qw422016.N().S(`	if !(`)
//line baked_in.qtpl:106
	StreamRegexValidation(qw422016, s, field, validation, "validator.HexcolorRegex")
//line baked_in.qtpl:106
	qw422016.N().S(`)() {
		verr = append(verr, validator.NewFieldError(validator.ErrIsDefault, "hexcolor", "`)
//line baked_in.qtpl:107
	qw422016.E().J(field.Identifier)
//line baked_in.qtpl:107
	qw422016.N().S(`", v.`)
//line baked_in.qtpl:107
	qw422016.E().S(field.Name)
//line baked_in.qtpl:107
	qw422016.N().S(`))
	}
`)
//line baked_in.qtpl:109
}

//line baked_in.qtpl:109
func WriteHexcolor(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:109
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:109
	StreamHexcolor(qw422016, s, field, validation)
//line baked_in.qtpl:109
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:109
}

//line baked_in.qtpl:109
func Hexcolor(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) string {
//line baked_in.qtpl:109
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:109
	WriteHexcolor(qb422016, s, field, validation)
//line baked_in.qtpl:109
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:109
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:109
	return qs422016
//line baked_in.qtpl:109
}

//line baked_in.qtpl:111
func StreamRGBa(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:111
	qw422016.N().S(`	if !(`)
//line baked_in.qtpl:112
	StreamRegexValidation(qw422016, s, field, validation, "validator.RgbaRegex")
//line baked_in.qtpl:112
	qw422016.N().S(`)() {
		verr = append(verr, validator.NewFieldError(validator.ErrIsDefault, "rgba", "`)
//line baked_in.qtpl:113
	qw422016.E().J(field.Identifier)
//line baked_in.qtpl:113
	qw422016.N().S(`", v.`)
//line baked_in.qtpl:113
	qw422016.E().S(field.Name)
//line baked_in.qtpl:113
	qw422016.N().S(`))
	}
`)
//line baked_in.qtpl:115
}

//line baked_in.qtpl:115
func WriteRGBa(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:115
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:115
	StreamRGBa(qw422016, s, field, validation)
//line baked_in.qtpl:115
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:115
}

//line baked_in.qtpl:115
func RGBa(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) string {
//line baked_in.qtpl:115
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:115
	WriteRGBa(qb422016, s, field, validation)
//line baked_in.qtpl:115
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:115
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:115
	return qs422016
//line baked_in.qtpl:115
}

//line baked_in.qtpl:117
func StreamRGB(qw422016 *qt422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:117
	qw422016.N().S(`	if !(`)
//line baked_in.qtpl:118
	StreamRegexValidation(qw422016, s, field, validation, "validator.RgbRegex")
//line baked_in.qtpl:118
	qw422016.N().S(`)() {
		verr = append(verr, validator.NewFieldError(validator.ErrIsDefault, "rgb", "`)
//line baked_in.qtpl:119
	qw422016.E().J(field.Identifier)
//line baked_in.qtpl:119
	qw422016.N().S(`", v.`)
//line baked_in.qtpl:119
	qw422016.E().S(field.Name)
//line baked_in.qtpl:119
	qw422016.N().S(`))
	}
`)
//line baked_in.qtpl:121
}

//line baked_in.qtpl:121
func WriteRGB(qq422016 qtio422016.Writer, s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) {
//line baked_in.qtpl:121
	qw422016 := qt422016.AcquireWriter(qq422016)
//line baked_in.qtpl:121
	StreamRGB(qw422016, s, field, validation)
//line baked_in.qtpl:121
	qt422016.ReleaseWriter(qw422016)
//line baked_in.qtpl:121
}

//line baked_in.qtpl:121
func RGB(s *validator.StructData, field *validator.FieldData, validation *validator.ValidationData) string {
//line baked_in.qtpl:121
	qb422016 := qt422016.AcquireByteBuffer()
//line baked_in.qtpl:121
	WriteRGB(qb422016, s, field, validation)
//line baked_in.qtpl:121
	qs422016 := string(qb422016.B)
//line baked_in.qtpl:121
	qt422016.ReleaseByteBuffer(qb422016)
//line baked_in.qtpl:121
	return qs422016
//line baked_in.qtpl:121
}
